name: Build-Linux

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.rst'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install prereqs
        run: |
          sudo apt-get update
          sudo apt-get install -y libgraphviz-dev libboost-all-dev
      - name: Install SimGrid
        run: |
          git clone https://framagit.org/simgrid/simgrid.git
          cd simgrid
          git checkout e3bfee0abad43d0b16c84b093b8c4d921fa91ddf
          mkdir build
          cd build
          cmake ..
          make -j4
          sudo make install

      - name: Install Google Tests
        run: |
          wget https://github.com/google/googletest/archive/refs/tags/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake .
          make -j4
          sudo make install

      - name: Install lcov
        run: |
          sudo apt-get -y install lcov

      - name: Build and run tests
        run: |
          git clone https://github.com/frs69wq/file-system-module.git
          cd file-system-module
          mkdir build
          cd build
          cmake ..
          make -j4 unit_tests
          ./unit_tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
#         directory: ./coverage/reports/
#         env_vars: OS,PYTHON
#         fail_ci_if_error: true
#         files: ./coverage1.xml,./coverage2.xml,!./cache
#         flags: unit_tests
#         name: codecov-umbrella

      - name: Install Doxygen and Sphinx
        run: |
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3-sphinx

      - name: Build and Deploy Documentation
        run: |
          #git clone https://github.com/frs69wq/file-system-module.git
          cd file-system-module
          mkdir build
          cd build
          cmake ..
          make doc




          



